"use client";
import { useCallback,useEffect,useState } from "react";
import { readSession } from "@/lib/auth-session";
import { sharingApi,type DashboardShare,type CreatedDashboardShare,type DashboardExport,type DeliverySchedule } from "@/lib/dashboard-sharing";

export function DashboardShareManager({dashboardId}:{dashboardId:string}) {
 const [session]=useState(()=>readSession()); const [links,setLinks]=useState<DashboardShare[]>([]); const [exports,setExports]=useState<DashboardExport[]>([]); const [schedules,setSchedules]=useState<DeliverySchedule[]>([]); const [created,setCreated]=useState<CreatedDashboardShare|null>(null); const [error,setError]=useState(""); const [password,setPassword]=useState(""); const [email,setEmail]=useState(""); const [recipients,setRecipients]=useState("");
 const load=useCallback(async()=>{if(!session)return;const [l,e,s]=await Promise.all([sharingApi.list(dashboardId,session.accessToken),sharingApi.exports(dashboardId,session.accessToken),sharingApi.schedules(dashboardId,session.accessToken)]);setLinks(l);setExports(e);setSchedules(s);},[dashboardId,session]);
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(e=>setError(e instanceof Error?e.message:"Error")),0);return()=>clearTimeout(timer);},[load]);
 async function create(){if(!session)return;try{setCreated(await sharingApi.create(dashboardId,session.accessToken,{expirationDays:30,password:password||null,recipientEmail:email||null,allowFilters:true,allowExport:true,allowEmbed:true}));await load();}catch(e){setError(e instanceof Error?e.message:"No se pudo crear el enlace.");}}
 async function download(item:DashboardExport){if(!session)return;const file=await sharingApi.downloadExport(dashboardId,item.id,session.accessToken);const url=URL.createObjectURL(file.blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=file.filename||item.fileName||"dashboard";anchor.click();URL.revokeObjectURL(url);}
 return <main className="provider-page"><header className="provider-hero"><div><p className="eyebrow">Distribución</p><h1>Compartir dashboard</h1><p>Enlaces, archivos e informes programados de la publicación vigente.</p></div></header>{error&&<div className="notice notice-error">{error}</div>}{created&&<section className="provider-card"><h2>Enlace creado</h2><input readOnly value={`${location.origin}${created.relativeUrl}`}/></section>}
 <section className="provider-card"><div className="section-heading"><h2>Enlaces públicos</h2><button className="primary-button" onClick={()=>void create()}>Crear enlace</button></div><div className="association-toolbar"><label>Contraseña opcional<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Destinatario opcional<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></div><div className="provider-sources">{links.map(x=><article key={x.id}><div><h3>{x.status}</h3><p>{x.accessCount} accesos · exportación {x.allowExport?"permitida":"bloqueada"}</p></div>{x.status==="Active"&&<button className="secondary-button" onClick={async()=>{if(session){await sharingApi.revoke(dashboardId,x.id,session.accessToken);await load();}}}>Revocar</button>}</article>)}</div></section>
 <section className="provider-card"><div className="section-heading"><div><h2>Exportaciones</h2><p>PDF, CSV y Excel se generan en segundo plano.</p></div><div>{["Pdf","Csv","Excel"].map(format=><button key={format} className="secondary-button" onClick={async()=>{if(session){await sharingApi.requestExport(dashboardId,session.accessToken,format);await load();}}}>{format}</button>)}</div></div><div className="provider-sources">{exports.map(x=><article key={x.id}><div><h3>{x.format} · {x.status}</h3><p>{new Date(x.createdAtUtc).toLocaleString("es-BO")}{x.errorCode?` · ${x.errorCode}`:""}</p></div>{x.status==="Completed"&&<button className="secondary-button" onClick={()=>void download(x)}>Descargar</button>}</article>)}</div></section>
 <section className="provider-card"><div className="section-heading"><div><h2>Entregas programadas</h2><p>La configuración rápida envía un PDF cada lunes a las 12:00 UTC.</p></div><button className="primary-button" onClick={async()=>{if(session){await sharingApi.createSchedule(dashboardId,session.accessToken,{recipients:recipients.split(",").map(x=>x.trim()).filter(Boolean),format:"Pdf",frequency:"Weekly",hourUtc:12,dayOfWeek:1,dayOfMonth:null,isEnabled:true});setRecipients("");await load();}}}>Programar</button></div><label>Destinatarios separados por coma<input value={recipients} onChange={e=>setRecipients(e.target.value)} placeholder="cliente@empresa.com"/></label><div className="provider-sources">{schedules.map(x=><article key={x.id}><div><h3>{x.frequency} · {x.format}</h3><p>{x.recipients.join(", ")} · próxima {new Date(x.nextRunAtUtc).toLocaleString("es-BO")}</p></div><button className="secondary-button" onClick={async()=>{if(session){await sharingApi.deleteSchedule(dashboardId,x.id,session.accessToken);await load();}}}>Eliminar</button></article>)}</div></section></main>;
}
