// <auto-generated />
using System;
using AnaliticAsd.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnaliticAsd.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AnalitiAdsDbContext))]
    [Migration("20260917212324_AddPersistentDashboards")]
    partial class AddPersistentDashboards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.Ad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_set_id");

                    b.Property<string>("ConfiguredStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("configured_status");

                    b.Property<string>("EffectiveStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("effective_status");

                    b.Property<bool>("IsPresentOnMeta")
                        .HasColumnType("boolean")
                        .HasColumnName("is_present_on_meta");

                    b.Property<DateTimeOffset>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("MetaAdId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("meta_ad_id");

                    b.Property<DateTimeOffset?>("MetaCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_created_at_utc");

                    b.Property<DateTimeOffset?>("MetaUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_updated_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AdSetId", "MetaAdId")
                        .IsUnique()
                        .HasDatabaseName("ux_ads_ad_set_meta_id");

                    b.ToTable("ads", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("connection_status");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MetaAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("meta_account_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_ad_accounts_client_id");

                    b.HasIndex("DataSourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_ad_accounts_data_source_id");

                    b.HasIndex("MetaAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_ad_accounts_meta_account_id");

                    b.HasIndex("DataSourceId", "ClientId")
                        .IsUnique();

                    b.ToTable("ad_accounts", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdAccountSync", b =>
                {
                    b.Property<Guid>("AdAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_account_id");

                    b.Property<int>("AdSetsSynced")
                        .HasColumnType("integer")
                        .HasColumnName("ad_sets_synced");

                    b.Property<int>("AdsSynced")
                        .HasColumnType("integer")
                        .HasColumnName("ads_synced");

                    b.Property<int>("CampaignsSynced")
                        .HasColumnType("integer")
                        .HasColumnName("campaigns_synced");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("AdAccountId");

                    b.ToTable("ad_account_syncs", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingEvent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("billing_event");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ConfiguredStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("configured_status");

                    b.Property<string>("EffectiveStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("effective_status");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<bool>("IsPresentOnMeta")
                        .HasColumnType("boolean")
                        .HasColumnName("is_present_on_meta");

                    b.Property<DateTimeOffset>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("MetaAdSetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("meta_ad_set_id");

                    b.Property<DateTimeOffset?>("MetaCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_created_at_utc");

                    b.Property<DateTimeOffset?>("MetaUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_updated_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OptimizationGoal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("optimization_goal");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "MetaAdSetId")
                        .IsUnique()
                        .HasDatabaseName("ux_ad_sets_campaign_meta_id");

                    b.ToTable("ad_sets", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_account_id");

                    b.Property<string>("ConfiguredStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("configured_status");

                    b.Property<string>("EffectiveStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("effective_status");

                    b.Property<bool>("IsPresentOnMeta")
                        .HasColumnType("boolean")
                        .HasColumnName("is_present_on_meta");

                    b.Property<DateTimeOffset>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("MetaCampaignId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("meta_campaign_id");

                    b.Property<DateTimeOffset?>("MetaCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_created_at_utc");

                    b.Property<DateTimeOffset?>("MetaUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_updated_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("objective");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<DateTimeOffset?>("StopsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stops_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AdAccountId", "MetaCampaignId")
                        .IsUnique()
                        .HasDatabaseName("ux_campaigns_account_meta_id");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.InsightSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_account_id");

                    b.Property<Guid?>("AdId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_id");

                    b.Property<Guid?>("AdSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_set_id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<decimal?>("Cpa")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("cpa");

                    b.Property<decimal?>("Cpc")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("cpc");

                    b.Property<decimal?>("Cpl")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("cpl");

                    b.Property<decimal?>("Cpm")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("cpm");

                    b.Property<decimal?>("Ctr")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("ctr");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal?>("Frequency")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("frequency");

                    b.Property<long?>("Impressions")
                        .HasColumnType("bigint")
                        .HasColumnName("impressions");

                    b.Property<decimal?>("Leads")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("leads");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<long?>("LinkClicks")
                        .HasColumnType("bigint")
                        .HasColumnName("link_clicks");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<string>("ObservedDataQuality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("LegacyZeroNormalized")
                        .HasColumnName("observed_data_quality");

                    b.Property<decimal?>("PurchaseValue")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("purchase_value");

                    b.Property<decimal?>("Purchases")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("purchases");

                    b.Property<long?>("Reach")
                        .HasColumnType("bigint")
                        .HasColumnName("reach");

                    b.Property<decimal?>("Roas")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)")
                        .HasColumnName("roas");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<decimal?>("Spend")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("spend");

                    b.HasKey("Id");

                    b.HasIndex("AdAccountId", "SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("ux_insight_snapshots_account_date")
                        .HasFilter("level = 'Account'");

                    b.HasIndex("AdId", "SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("ux_insight_snapshots_ad_date")
                        .HasFilter("level = 'Ad'");

                    b.HasIndex("AdSetId", "SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("ux_insight_snapshots_adset_date")
                        .HasFilter("level = 'AdSet'");

                    b.HasIndex("CampaignId", "SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("ux_insight_snapshots_campaign_date")
                        .HasFilter("level = 'Campaign'");

                    b.ToTable("insight_snapshots", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "Name")
                        .HasDatabaseName("ix_clients_agency_id_name");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Dashboards.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int?>("CurrentPublicationNumber")
                        .HasColumnType("integer")
                        .HasColumnName("current_publication_number");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ClientId", "AgencyId");

                    b.HasIndex("FolderId", "ClientId", "AgencyId");

                    b.HasIndex("AgencyId", "ClientId", "FolderId", "ArchivedAtUtc")
                        .HasDatabaseName("ix_dashboards_workspace_folder_archive");

                    b.ToTable("dashboards", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Dashboards.DashboardDraft", b =>
                {
                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("dashboard_id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("DashboardId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("DashboardId", "ClientId", "AgencyId")
                        .IsUnique();

                    b.ToTable("dashboard_drafts", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Dashboards.DashboardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ClientId", "AgencyId");

                    b.HasIndex("AgencyId", "ClientId", "Name")
                        .HasDatabaseName("ix_dashboard_templates_scope_name");

                    b.ToTable("dashboard_templates", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Dashboards.DashboardVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("dashboard_id");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("definition_hash");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<int>("DraftRevision")
                        .HasColumnType("integer")
                        .HasColumnName("draft_revision");

                    b.Property<int>("PublicationNumber")
                        .HasColumnType("integer")
                        .HasColumnName("publication_number");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("DashboardId", "PublicationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_dashboard_versions_publication");

                    b.HasIndex("DashboardId", "ClientId", "AgencyId");

                    b.ToTable("dashboard_versions", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.DataSources.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateOnly?>("AvailableSince")
                        .HasColumnType("date")
                        .HasColumnName("available_since");

                    b.Property<DateOnly?>("AvailableUntil")
                        .HasColumnType("date")
                        .HasColumnName("available_until");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<Guid?>("ProviderConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_connection_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source_type");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "ClientId");

                    b.HasIndex("ClientId", "AgencyId");

                    b.HasIndex("ProviderConnectionId", "AgencyId");

                    b.HasIndex("AgencyId", "Provider", "SourceType", "ExternalId")
                        .IsUnique();

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.DataSources.ProviderConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("AuthorizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorized_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ExternalSubjectId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("external_subject_id");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_error_code");

                    b.Property<DateTimeOffset?>("LastSucceededAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_succeeded_at_utc");

                    b.Property<string>("ProtectedCredentialPayload")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("protected_credential_payload");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "Provider");

                    b.ToTable("provider_connections", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Folders.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_folder_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "AgencyId");

                    b.HasIndex("AgencyId", "ClientId", "ArchivedAtUtc")
                        .HasDatabaseName("ix_folders_workspace_archive");

                    b.HasIndex("ParentFolderId", "ClientId", "AgencyId");

                    b.HasIndex("AgencyId", "ClientId", "ParentFolderId", "SortOrder")
                        .HasDatabaseName("ix_folders_workspace_parent_sort");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("agencies", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.ClientAccess", b =>
                {
                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at_utc");

                    b.HasKey("AgencyId", "ClientId", "UserId");

                    b.HasIndex("AgencyId", "UserId");

                    b.HasIndex("ClientId", "AgencyId");

                    b.ToTable("client_accesses", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.ClientEditorAssignment", b =>
                {
                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at_utc");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("AgencyId", "ClientId", "UserId");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("AgencyId", "UserId")
                        .HasDatabaseName("ix_client_editor_assignments_agency_user");

                    b.HasIndex("ClientId", "AgencyId");

                    b.ToTable("client_editor_assignments", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.ClientInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AgencyId", "ClientId");

                    b.HasIndex("ClientId", "AgencyId");

                    b.ToTable("client_invitations", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.McpAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "OccurredAtUtc");

                    b.ToTable("mcp_audit_events", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.McpConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("scopes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AgencyId", "UserId");

                    b.ToTable("mcp_connections", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.Membership", b =>
                {
                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.HasKey("AgencyId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_memberships_user_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Meta.MetaConnection", b =>
                {
                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ProtectedAccessToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("protected_access_token");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("AgencyId");

                    b.ToTable("meta_connections", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_account_id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<DateOnly>("Since")
                        .HasColumnType("date")
                        .HasColumnName("since");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("snapshot_hash");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateOnly>("Until")
                        .HasColumnType("date")
                        .HasColumnName("until");

                    b.HasKey("Id");

                    b.HasIndex("AdAccountId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ClientId", "AgencyId");

                    b.HasIndex("AgencyId", "ClientId", "CreatedAtUtc");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Reports.ReportShareAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation");

                    b.Property<Guid>("ShareLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_link_id");

                    b.HasKey("Id");

                    b.HasIndex("ShareLinkId", "OccurredAtUtc");

                    b.ToTable("report_share_audit_events", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Reports.ReportShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ReportId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AgencyId", "ReportId");

                    b.ToTable("report_share_links", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.Ad", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Advertising.AdSet", null)
                        .WithMany()
                        .HasForeignKey("AdSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdAccount", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.DataSources.DataSource", "DataSource")
                        .WithOne()
                        .HasForeignKey("AnaliticAsd.Domain.Advertising.AdAccount", "DataSourceId", "ClientId")
                        .HasPrincipalKey("AnaliticAsd.Domain.DataSources.DataSource", "Id", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdAccountSync", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Advertising.AdAccount", null)
                        .WithOne()
                        .HasForeignKey("AnaliticAsd.Domain.Advertising.AdAccountSync", "AdAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdSet", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Advertising.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.Campaign", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Advertising.AdAccount", null)
                        .WithMany()
                        .HasForeignKey("AdAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.InsightSnapshot", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Advertising.AdAccount", null)
                        .WithMany()
                        .HasForeignKey("AdAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Advertising.Ad", null)
                        .WithMany()
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AnaliticAsd.Domain.Advertising.AdSet", null)
                        .WithMany()
                        .HasForeignKey("AdSetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AnaliticAsd.Domain.Advertising.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Clients.Client", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Dashboards.Dashboard", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Folders.Folder", null)
                        .WithMany()
                        .HasForeignKey("FolderId", "ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "ClientId", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Dashboards.DashboardDraft", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Dashboards.Dashboard", null)
                        .WithOne()
                        .HasForeignKey("AnaliticAsd.Domain.Dashboards.DashboardDraft", "DashboardId", "ClientId", "AgencyId")
                        .HasPrincipalKey("AnaliticAsd.Domain.Dashboards.Dashboard", "Id", "ClientId", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Dashboards.DashboardTemplate", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Dashboards.DashboardVersion", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Dashboards.Dashboard", null)
                        .WithMany()
                        .HasForeignKey("DashboardId", "ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "ClientId", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.DataSources.DataSource", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.DataSources.ProviderConnection", null)
                        .WithMany()
                        .HasForeignKey("ProviderConnectionId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.DataSources.ProviderConnection", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Folders.Folder", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Folders.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId", "ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "ClientId", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.ClientAccess", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Membership", null)
                        .WithMany()
                        .HasForeignKey("AgencyId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.ClientEditorAssignment", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Identity.Membership", null)
                        .WithMany()
                        .HasForeignKey("AgencyId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.ClientInvitation", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.McpAuditEvent", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.McpConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.McpConnection", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.Membership", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Meta.MetaConnection", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Agency", null)
                        .WithOne()
                        .HasForeignKey("AnaliticAsd.Domain.Meta.MetaConnection", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Reports.Report", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Advertising.AdAccount", null)
                        .WithMany()
                        .HasForeignKey("AdAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId", "AgencyId")
                        .HasPrincipalKey("Id", "AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Reports.ReportShareAuditEvent", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Reports.ReportShareLink", null)
                        .WithMany()
                        .HasForeignKey("ShareLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Reports.ReportShareLink", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Reports.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
