// <auto-generated />
using System;
using AnaliticAsd.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnaliticAsd.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AnalitiAdsDbContext))]
    [Migration("20260904184710_AddAdvertisingHierarchy")]
    partial class AddAdvertisingHierarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.Ad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_set_id");

                    b.Property<string>("ConfiguredStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("configured_status");

                    b.Property<string>("EffectiveStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("effective_status");

                    b.Property<bool>("IsPresentOnMeta")
                        .HasColumnType("boolean")
                        .HasColumnName("is_present_on_meta");

                    b.Property<DateTimeOffset>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("MetaAdId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("meta_ad_id");

                    b.Property<DateTimeOffset?>("MetaCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_created_at_utc");

                    b.Property<DateTimeOffset?>("MetaUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_updated_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AdSetId", "MetaAdId")
                        .IsUnique()
                        .HasDatabaseName("ux_ads_ad_set_meta_id");

                    b.ToTable("ads", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("connection_status");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MetaAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("meta_account_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_ad_accounts_client_id");

                    b.HasIndex("MetaAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_ad_accounts_meta_account_id");

                    b.ToTable("ad_accounts", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdAccountSync", b =>
                {
                    b.Property<Guid>("AdAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_account_id");

                    b.Property<int>("AdSetsSynced")
                        .HasColumnType("integer")
                        .HasColumnName("ad_sets_synced");

                    b.Property<int>("AdsSynced")
                        .HasColumnType("integer")
                        .HasColumnName("ads_synced");

                    b.Property<int>("CampaignsSynced")
                        .HasColumnType("integer")
                        .HasColumnName("campaigns_synced");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("AdAccountId");

                    b.ToTable("ad_account_syncs", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingEvent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("billing_event");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ConfiguredStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("configured_status");

                    b.Property<string>("EffectiveStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("effective_status");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<bool>("IsPresentOnMeta")
                        .HasColumnType("boolean")
                        .HasColumnName("is_present_on_meta");

                    b.Property<DateTimeOffset>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("MetaAdSetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("meta_ad_set_id");

                    b.Property<DateTimeOffset?>("MetaCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_created_at_utc");

                    b.Property<DateTimeOffset?>("MetaUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_updated_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OptimizationGoal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("optimization_goal");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "MetaAdSetId")
                        .IsUnique()
                        .HasDatabaseName("ux_ad_sets_campaign_meta_id");

                    b.ToTable("ad_sets", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ad_account_id");

                    b.Property<string>("ConfiguredStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("configured_status");

                    b.Property<string>("EffectiveStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("effective_status");

                    b.Property<bool>("IsPresentOnMeta")
                        .HasColumnType("boolean")
                        .HasColumnName("is_present_on_meta");

                    b.Property<DateTimeOffset>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("MetaCampaignId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("meta_campaign_id");

                    b.Property<DateTimeOffset?>("MetaCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_created_at_utc");

                    b.Property<DateTimeOffset?>("MetaUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meta_updated_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("objective");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<DateTimeOffset?>("StopsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stops_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AdAccountId", "MetaCampaignId")
                        .IsUnique()
                        .HasDatabaseName("ux_campaigns_account_meta_id");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId", "Name")
                        .HasDatabaseName("ix_clients_agency_id_name");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("agencies", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.Membership", b =>
                {
                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.HasKey("AgencyId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_memberships_user_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Meta.MetaConnection", b =>
                {
                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ProtectedAccessToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("protected_access_token");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("AgencyId");

                    b.ToTable("meta_connections", (string)null);
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.Ad", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Advertising.AdSet", null)
                        .WithMany()
                        .HasForeignKey("AdSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdAccount", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdAccountSync", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Advertising.AdAccount", null)
                        .WithOne()
                        .HasForeignKey("AnaliticAsd.Domain.Advertising.AdAccountSync", "AdAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.AdSet", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Advertising.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Advertising.Campaign", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Advertising.AdAccount", null)
                        .WithMany()
                        .HasForeignKey("AdAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Clients.Client", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Identity.Membership", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnaliticAsd.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnaliticAsd.Domain.Meta.MetaConnection", b =>
                {
                    b.HasOne("AnaliticAsd.Domain.Identity.Agency", null)
                        .WithOne()
                        .HasForeignKey("AnaliticAsd.Domain.Meta.MetaConnection", "AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
